# tokens and cookies configurations
secret_key_base: '621d878119cb93a899add5f4deb404f071097256bb0ba9376c351f54ca19b3a7eb40629f3bb760be1d931ff05a5903d9f43ba3796de990b6558d560e4b81df61'
session_name: '_quizzing_session'
default_password: 'cffde42269510ac7d1f37ded208daad1'

# database configurations
dev_database: 'quizzing_dev'
test_database: 'quizzing_test'
production_database: 'quizzing'
db_user: 'quizzing'
db_password: 'quizmaster!'

# mailer configurations
mailer_service: 'smtp.gmail.com'
mailer_user: 'biblequizstats.net'
mailer_password: 'Iwryftytlhe'